/**
 * /improvement — Bounded Self-Improvement Loop
 *
 * Displays pending improvement proposals. Human approval required before
 * execution of any proposal. Auto-apply is NEVER permitted on constitutional
 * surfaces. See: packages/tlc-research-kernel/src/improvement-proposer.ts
 */
export const dynamic = "force-dynamic";

async function loadProposals() {
  const fs = await import("fs/promises");
  const path = await import("path");
  const root = process.cwd().includes("apps/tlc-control-plane")
    ? path.resolve(process.cwd(), "../../..")
    : process.cwd();
  try {
    const raw = await fs.readFile(path.join(root, "research/registry/improvement_proposals.json"), "utf-8");
    return { data: JSON.parse(raw), error: null };
  } catch (e) {
    return { data: null, error: String(e) };
  }
}

export default async function ImprovementPage() {
  const { data, error } = await loadProposals();

  return (
    <main className="p-6 space-y-6">
      <header>
        <h1 className="text-2xl font-bold text-white">Self-Improvement Loop</h1>
        <p className="text-sm text-gray-400 mt-1">
          Bounded improvement proposals. Human approval gate is mandatory.
          Auto-apply is never permitted on constitutional surfaces.
        </p>
      </header>

      <div className="border border-gray-800 rounded p-4 bg-gray-950 text-sm">
        <span className="text-gray-500">Approval gate:</span>{" "}
        <span className="text-red-400 font-mono">{data?.approval_gate ?? "MANDATORY"}</span>
      </div>

      {error && (
        <div className="border border-yellow-600 bg-yellow-950 p-4 rounded text-yellow-300 text-sm">
          {error}
        </div>
      )}

      {data?.proposals?.length === 0 && (
        <div className="border border-dashed border-gray-700 rounded p-8 text-center">
          <p className="text-gray-500 text-sm">No improvement proposals pending.</p>
          <p className="text-gray-600 text-xs mt-2">
            Proposals are generated by the constitutional critic and require human review.
          </p>
        </div>
      )}

      {data?.proposals?.map((p: Record<string, unknown>, idx: number) => (
        <div key={String(p.id ?? idx)} className="border border-gray-700 rounded p-4 bg-gray-900">
          <div className="flex items-center gap-3 mb-2">
            <span className="text-white font-mono text-sm">{String(p.id)}</span>
            <span className={`text-xs px-2 py-0.5 rounded ${
              String(p.status) === "pending_review"
                ? "bg-yellow-900 text-yellow-300"
                : "bg-gray-700 text-gray-400"
            }`}>
              {String(p.status ?? "unknown")}
            </span>
            {Boolean(p.is_authoritative_surface) && (
              <span className="text-xs px-2 py-0.5 rounded bg-red-900 text-red-300">
                PROTECTED SURFACE — human review required
              </span>
            )}
          </div>
          <p className="text-gray-300 text-sm">{String(p.title ?? "")}</p>
          <p className="text-gray-500 text-xs mt-1">{String(p.description ?? "")}</p>
        </div>
      ))}
    </main>
  );
}
